server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
            set $backend_host http://backend:8080;
       # proxy_pass https://book-reviews-backend-j15p.onrender.com; 
         proxy_pass $backend_host/api/;
        proxy_set_header Host $host;
       # proxy_set_header Host https://book-reviews-backend-j15p.onrender.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }
}
